### ISSUE TITLE
ScanMapCB panics with a nil or invalid memory address

### ISSUE THREAD

**Issue by TerminalFi** [ca110us/go-clamav#3]
The following code fails to scan a string

`code, virus, err := scanEngine.Scan([]byte("X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*"))`

```go
func (in *Instance) Scan(content []byte) (uint, string, error) {
	in.logger.Info("configuring memory")
	fmap := goclamav.OpenMemory(content)

	in.logger.Info("scanning file")
	code, virus, err := in.clamav.ScanMapCB(fmap, "7391F8C8-1E6E-4A40-9129-4EAEA3E9EF11.pdf", context.TODO())
	if err != nil {
		return 0, "", err
	}

	in.logger.WithFields(
		logrus.Fields{"result": code,
			"name": virus}).Info("scan results")
	return code, virus, nil

}
```

**Comment by ca110us** [comment]
I tried the following code and it works, do you have the detailed stack information?

```go
fmap := goclamav.OpenMemory([]byte("X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*"))
 code, virus, err := engine.ScanMapCB(fmap, "engine.go", context.TODO()) 
fmt.Println(code, virus, err)
```

**Comment by TerminalFi** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x54bc47]

goroutine 1 [running]:
github.com/ca110us/go-clamav.(*Clamav).ScanFile.func2(0xe132c0?, 0x6?, 0x46be3e?, 0x585620?)
	/root/go/pkg/mod/github.com/ca110us/go-clamav@v0.5.5/clamav.go:226 +0x27
github.com/ca110us/go-clamav.(*Clamav).ScanFile(0xc0000ca070?, {0x5910ab?, 0xc0000c1a50?})
	/root/go/pkg/mod/github.com/ca110us/go-clamav@v0.5.5/clamav.go:226 +0xb7
projectio/internal/scanner.(*Instance).Scan(0xc000012060, {0xc00001e050?, 0xc0000c1c58?, 0x1?})
	projectio/internal/scanner/scanner.go:72 +0xc5
projectio/cli/cmd.glob..func1(0x6bcf20?, {0x590d6f?, 0x0?, 0x0?})
	projectio/cli/cmd/serve.go:21 +0x225
github.com/spf13/cobra.(*Command).execute(0x6bcf20, {0x702938, 0x0, 0x0})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x6bcca0)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
projectio/cli/cmd.Execute()
	projectio/cli/cmd/root.go:31 +0x25
main.main()
	projectio/main.go:10 +0x17
	```

**Comment by TerminalFi** [comment]
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/32599364/166950994-f8e23aec-fc0b-4cdc-8403-3bb87b22ffc7.png">

**Comment by ca110us** [comment]
It looks like you're calling ScanFile instead of ScanMapCB, did you initialize the clamav engine in correctly?

**Comment by TerminalFi** [comment]
Miss copy.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x54c774]

goroutine 1 [running]:
github.com/ca110us/go-clamav.(*Clamav).ScanMapCB.func2(0x1f28c40, 0xc0000bc008?, 0x7f827d9795b8?, 0x30?, 0x6d61a0?, 0xc0000a4c00?)
	/root/go/pkg/mod/github.com/ca110us/go-clamav@v0.5.5/clamav.go:201 +0x34
github.com/ca110us/go-clamav.(*Clamav).ScanMapCB(0xc0000ce070?, 0x1f28c40, {0x59afcb, 0x28}, {0x57a620, 0xc0000bc008})
	/root/go/pkg/mod/github.com/ca110us/go-clamav@v0.5.5/clamav.go:201 +0x145
projectio/internal/scanner.(*Instance).Scan(0xc0000ac120, {0xc0000e8050, 0x44, 0x44})
	/go/src/projectio/internal/scanner/scanner.go:73 +0x215
projectio/cli/cmd.glob..func1(0x6bef20?, {0x591f8f?, 0x0?, 0x0?})
	/go/src/projectio/cli/cmd/serve.go:21 +0x225
github.com/spf13/cobra.(*Command).execute(0x6bef20, {0x704938, 0x0, 0x0})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x6beca0)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
projectio/cli/cmd.Execute()
	/go/src/projectio/cli/cmd/root.go:31 +0x25
main.main()
	/go/src/projectio/main.go:10 +0x17
```

**Comment by TerminalFi** [comment]
Initialization

```go
func New(config any, logger *logrus.Logger) (*Instance, error) {
	if logger == nil {
		return nil, errors.New("logger is nil")
	}

	c := new(goclamav.Clamav)
	err := c.Init(goclamav.SCAN_OPTIONS{
		General:   0,
		Parse:     goclamav.CL_SCAN_PARSE_PDF | goclamav.CL_SCAN_PARSE_ARCHIVE,
		Heuristic: 0,
		Mail:      0,
		Dev:       0,
	})

	if err != nil {
		return nil, err
	}

	// load db
	signo, err := c.LoadDB("./", uint(goclamav.CL_DB_DIRECTORY))
	if err != nil {
		return nil, err
	}

	logger.Info(signo)

	// compile engine
	err = c.CompileEngine()
	if err != nil {
		return nil, err
	}

	c.EngineSetNum(goclamav.CL_ENGINE_MAX_SCANSIZE, 1024*1024*40)
	c.EngineSetNum(goclamav.CL_ENGINE_MAX_SCANTIME, 9000)

	return &Instance{
		config: nil,
		logger: logger,
	}, nil
}
```

**Comment by TerminalFi** [comment]
FWIW. I tried with the nmap file using ScanFile and it also didn't work. 

I will try to downgrade to clamav 0.104.0 and see if I get the same results.

If that doesn't work, I guess I will try your exact clamav install process

**Comment by ca110us** [comment]
Code looks fine, is there a clamav db file in the . / directory ?

**Comment by TerminalFi** [comment]
<img width="701" alt="image" src="https://user-images.githubusercontent.com/32599364/166968547-ac9430df-50ba-4cba-8581-e87cd9c0385f.png">

**Comment by ca110us** [comment]
The cvd and dat files must be in the same directory as the .go file you are executing.

**Comment by TerminalFi** [comment]
It is, you can see the compiled binary called scanio.

**Comment by ca110us** [comment]
It's a bit strange, but the problem should be that the pointer to the clamav engine instance is nil, maybe you should check the code again properly, use version 0.104.2 and follow the README steps to install clamav.

**Comment by TerminalFi** [comment]
It is very odd. 

I've installed with your exact steps. Here is the full code.

```go
package scanner

import (
	"context"
	"errors"

	goclamav "github.com/ca110us/go-clamav"
	"github.com/sirupsen/logrus"
)

type Scanner interface {
	Scan([]byte) (uint, string, error)
}

type Instance struct {
	config any
	logger *logrus.Logger
	clamav *goclamav.Clamav
}

func New(config any, logger *logrus.Logger) (*Instance, error) {
	if logger == nil {
		return nil, errors.New("logger is nil")
	}

	c := new(goclamav.Clamav)
	err := c.Init(goclamav.SCAN_OPTIONS{
		General:   0,
		Parse:     goclamav.CL_SCAN_PARSE_PDF | goclamav.CL_SCAN_PARSE_ARCHIVE,
		Heuristic: 0,
		Mail:      0,
		Dev:       0,
	})

	if err != nil {
		return nil, err
	}

	// load db
	signo, err := c.LoadDB("./", uint(goclamav.CL_DB_DIRECTORY))
	if err != nil {
		return nil, err
	}

	logger.Info(signo)

	// compile engine
	err = c.CompileEngine()
	if err != nil {
		return nil, err
	}

	c.EngineSetNum(goclamav.CL_ENGINE_MAX_SCANSIZE, 1024*1024*40)
	c.EngineSetNum(goclamav.CL_ENGINE_MAX_SCANTIME, 9000)

	return &Instance{
		config: nil,
		logger: logger,
	}, nil
}

func (in *Instance) Shutdown() error {
	return in.clamav.Free()
}

func (in *Instance) Scan(content []byte) (uint, string, error) {
	in.logger.Info("configuring memory", content)
	fmap := goclamav.OpenMemory(content)
	in.logger.Info("defer memory close")
	defer goclamav.CloseMemory(fmap)

	in.logger.Info("scanning file")
	// compile engine
	err := in.clamav.CompileEngine()
	if err != nil {
		return 0, "", err
	}

	in.clamav.EngineSetNum(goclamav.CL_ENGINE_MAX_SCANSIZE, 1024*1024*40)
	in.clamav.EngineSetNum(goclamav.CL_ENGINE_MAX_SCANTIME, 9000)

	err = in.clamav.CvdVerify("./daily.cvd")
	if err != nil {
		return 0, "", err
	}

	code, virus, err := in.clamav.ScanMapCB(fmap, "test.tmp", context.TODO())
	if err != nil {
		return 0, "", err
	}

	in.logger.WithFields(
		logrus.Fields{"result": code,
			"name": virus}).Info("scan results")
	return code, virus, nil

}

```


```dockerfile
FROM debian:latest as scanio

# Install Build Dependencies
RUN	apt-get update && apt-get install -y \
	`# install tools for building` \
	gcc make pkg-config python3 python3-pip python3-pytest valgrind \
	`# install clamav dependencies` \
	check libbz2-dev libcurl4-openssl-dev libjson-c-dev libmilter-dev \
	libncurses5-dev libpcre2-dev libssl-dev libxml2-dev zlib1g-dev \
	`# install curl temporarily` \
	curl git

RUN python3 -m pip install --user cmake

RUN apt-get install -y cmake

# Install ClamAV
RUN curl -L -k https://www.clamav.net/downloads/production/clamav-0.104.2.tar.gz --output clamav-0.104.2.tar.gz && \
	tar xzf clamav-0.104.2.tar.gz && \
	cd clamav-0.104.2 && \
	mkdir build && cd build && \
	`# Building ClamAV Lib` && \
	cmake .. && \
	cmake --build . && \
	ctest && \
	cmake --build . --target install


# Install Golang Binary
RUN curl -L -k https://go.dev/dl/go1.18.1.linux-amd64.tar.gz --output go1.18.1.linux-amd64.tar.gz && \
	tar -C /usr/local -xzf go1.18.1.linux-amd64.tar.gz && \
	export PATH=$PATH:/usr/local/go/bin

RUN apt remove -y curl

RUN mkdir /var/log/clamav
RUN mkdir /root/db

# TODO update with User that this will run
COPY freshclam.conf /usr/local/etc/freshclam.conf


# TODO this command needs run periodically via the golang tool as well
RUN freshclam --datadir=/root/

WORKDIR /go/src/gitlab.com/projectio/security/scanio

COPY . ./

RUN LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib \
	CGO_LDFLAGS="-L/usr/local/lib -lclamav" \
	GIT_SSL_NO_VERIFY=1 \
	GOPROXY="direct" \
	GOINSECURE="proxy.golang.org/*,github.com,github.com/*,golang.org,golang.org/*" \
	GOOS=linux \
	GOARCH=amd64 \
	/usr/local/go/bin/go build  -o ../../../../../../root/scanio .


WORKDIR /root

CMD ["LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib", "CGO_LDFLAGS=\"-L/usr/local/lib -lclamav\"", "./scanio", "serve"]  

```

**Comment by TerminalFi** [comment]
Ahhh I total see my issue. You were right about the nil pointer.
